[package]
name = "captcha-rs"
version = "0.2.12"
edition = "2021"
authors = ["Samir Djelal <ssdjelal@gmail.com>", "Web-Coke <web-chang@foxmail.com>"]
readme = "README.md"
repository = "https://github.com/samirdjelal/captcha-rs"
license = "MIT"
homepage ="https://github.com/samirdjelal/captcha-rs"
documentation = "https://github.com/samirdjelal/captcha-rs/blob/main/README.md"
keywords = ["captcha-rs", "captcha"]
description = "Generate verification images dynamically"
exclude = [
    "images/*",
]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.16"
rand = "0.9.0"
image = { version = "0.25.5", default-features = false, features = ["jpeg"] }
base64 = "0.22.1"
imageproc= "0.25.0"
ab_glyph = "0.2.29"
